### PR TITLE
Update VM to latest

### PR DESCRIPTION
**Pull request by axic**
Made some of these updates back in December, just never got to fully finish them. This version seems to be working, updated to the very latest ethereumjs-vm.

### CODE REVIEW

**Comment by axic** [comment]
Seems like this repo is not-maintained and development moved to `browser-solidity`?

**Comment by d11e9** [comment]
Just saw email notice of this issue, yes this library ended up refactored back into browser-solidity whence it came.

d11e9

**Comment by axic** [comment]
Would it make sense  putting a big warning note in the README mentioning it is not maintained and please use browser-solidity?

**Comment by d11e9** [comment]
@axic thanks for your work, merged all the same.

**Pull request merged**
